### ISSUE TITLE
compile errors on mac osx and freebsd

### ISSUE THREAD

**Issue by einthusan** [dwbuiten/go-mediainfo#1]
I have fixed this for my own version of freebsd... I gave up on mac osx... if you like, we can discuss about this topic further.

**Comment by einthusan** [comment]
just for reference, i ran into this issue again.. now 1 year later.. and realized that for the mac osx (el capitan) i need to do the following...

```
brew update
brew install media-info
export C_INCLUDE_PATH=/usr/local/include
```

**Comment by ridhoperdana** [comment]
@einthusan i did what you do to solve the problem on osx (i use sierra)
```
brew update
brew install media-info
export C_INCLUDE_PATH=/usr/local/include
```

but I still got `Undefined symbols for architecture x86_64`. Did you already solve the problem?

**Comment by einthusan** [comment]
@ridhoperdana I am using High Sierra now... i tested it and had no problems at all. Do you not want to update to High Sierra from Sierra?

Edit: update your Xcode as well
Edit: my go version is `go version go1.9.4 darwin/amd64`
